version: "1"
services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - "7200:7200"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
