name: Testing on npm test
on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing packages
        run: npm ci
      - name: running tests
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
